# Generated by Django 4.2.1 on 2023-07-07 18:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='research_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=3),
        ),
    ]
