# Generated by Django 4.2.1 on 2023-07-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_research_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='research_areas',
        ),
    ]
