# Generated by Django 4.2.1 on 2023-07-09 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_research_areas_researcharea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcharea',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_areas', to=settings.AUTH_USER_MODEL),
        ),
    ]
