# Generated by Django 4.2.1 on 2023-07-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_researcharea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcharea',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
