# Generated by Django 4.2.1 on 2023-06-19 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='submitters',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='conferences',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='submitters',
        ),
        migrations.AddField(
            model_name='paper',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.conference'),
        ),
        migrations.AddField(
            model_name='paper',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conference',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
