# Generated by Django 4.2.1 on 2023-06-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_author_created_at_author_updated_at_conference_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
