# Generated by Django 4.2.1 on 2023-07-02 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_reviewer_paper_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
