# Generated by Django 4.2.1 on 2023-06-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_alter_conference_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='conference',
            new_name='conferences',
        ),
    ]
