# Generated by Django 4.2.1 on 2023-06-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_rename_conference_paper_conferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, to='conference.author'),
        ),
    ]
