# Generated by Django 4.2.1 on 2023-07-02 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0004_reviewer_created_at_reviewer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='first_name',
            field=models.CharField(default='Happy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='last_name',
            field=models.CharField(default='Jo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
