# Generated by Django 4.2.1 on 2023-06-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_alter_paper_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
    ]
