# Generated by Django 4.2.1 on 2023-07-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_reviewer_email_reviewer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='reviewers',
        ),
    ]
