# Generated by Django 4.2.1 on 2023-07-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_remove_paper_reviewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.paper')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.reviewer')),
            ],
            options={
                'unique_together': {('paper_id', 'reviewer_id')},
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='reviewers',
            field=models.ManyToManyField(through='conference.Paper_Reviewer', to='conference.reviewer'),
        ),
    ]
