# Generated by Django 4.2.1 on 2023-06-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_remove_paper_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='submitter',
            new_name='giver',
        ),
    ]
