# Generated by Django 4.2.1 on 2023-06-04 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0007_rename_submitter_paper_giver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='giver',
        ),
        migrations.AddField(
            model_name='paper',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper',
            name='conferences',
            field=models.ManyToManyField(blank=True, to='conference.conference'),
        ),
    ]
