# Generated by Django 4.2.1 on 2023-07-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_paper_reviewer_paper_reviewers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper_reviewer',
            old_name='paper_id',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='paper_reviewer',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
