# Generated by Django 4.2.1 on 2023-06-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_remove_paper_giver_paper_submitter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='slug',
        ),
    ]
