# Generated by Django 4.2.1 on 2023-07-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_rename_paper_id_paper_reviewer_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_reviewer',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
