# Generated by Django 4.2.1 on 2023-07-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
