# Generated by Django 4.2.1 on 2023-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_alter_paper_abstract_alter_paper_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(unique=True, upload_to='conference/papers'),
        ),
    ]
