# Generated by Django 4.2.1 on 2023-06-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_alter_paper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='conference/papers'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
