# Generated by Django 4.2.1 on 2023-06-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_alter_paper_abstract_alter_paper_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='file_hash',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
